baseURL = "https://nosuchdomain.mooo.com/site/"
languageCode = "en-us"
title = "Hugo Ncurses"
copyright = "Copyright 2020 Johannes Marbach"
theme = "hugo-theme-ncurses"

[params]
  mainSections = ["posts"]

[menu]
	[[menu.main]]
		identifier = "home"
		name = "Home"
		title = "?"
		url = "/"
		weight = 1
